@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhODdlNDk4MS0xOWZiLTQ3MDYtOTgwZS04ZWQwMGIxYTIwOGQiLCJlbWFpbCI6ImV4Y29kZS5uZXRAZ21haWwuY29tIiwidWlkIjoiMTE3MjcwIiwibmFtZSI6IkFmbmFuIEFobWVkIiwidXNlcm5hbWUiOiJhZm5hbiIsImNvdW50cnkiOiIxMzAiLCJtb2JpbGVubyI6IjYwMTc2NzAxOTQ1IiwicmVmcmVzaEtleSI6Imx6SDlZR1hKWEdVM3JHek9zUU12clE9PSIsImlhdCI6MTcyMzYwOTU4NiwiZXhwIjoxNzI2MjAxNTg2fQ.dD6alKmO2xpiL6hUvNfxvoS2JXZH7NaVjlBmRXRLvo4
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/bank HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}

###

GET {{HOST}}/bank? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bank?bank_id=1&bank_name=occaecat&bank_logo_url=https://uc HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}
###
PATCH {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}
###
DELETE {{HOST}}/bank/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
