@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/bankdocument HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"acc_no":"labore",
"bankimgname":"aliqua",
"bankimgstring":"Anim reprehenderit labore sit aliquip esse.",
"uid":"velit"
}

###

GET {{HOST}}/bankdocument? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bankdocument?acc_no=labore&bankimgname=aliqua&bankimgstring=Anim repre&uid=velit HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bankdocument/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/bankdocument/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"acc_no":"labore",
"bankimgname":"aliqua",
"bankimgstring":"Anim reprehenderit labore sit aliquip esse.",
"uid":"velit"
}
###
PATCH {{HOST}}/bankdocument/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"acc_no":"labore",
"bankimgname":"aliqua",
"bankimgstring":"Anim reprehenderit labore sit aliquip esse.",
"uid":"velit"
}
###
DELETE {{HOST}}/bankdocument/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
