@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDJkMDIwZC1kNmUzLTQxOTQtODZjOC0yOTRmYzBiNDIwZGQiLCJlbWFpbCI6ImthemFkNzlAZ21haWwuY29tIiwidWlkIjoiMCIsIm5hbWUiOiJrYWxhbSBBemFkIiwidXNlcm5hbWUiOiJrYWxhbSIsImNvdW50cnkiOiIxMzAiLCJtb2JpbGVubyI6IjYwMTc2NzAxMjIiLCJyZWZyZXNoS2V5IjoiMllSdXAxaXFZODJoTnNmZ3JGN0lpQT09IiwiaWF0IjoxNzI4NDY1NTcwLCJleHAiOjE3Mjg2MzgzNzB9.Vz1h45RDGfFKNLWEjEebnM6pFnlImG3eIRvUIG7c3QQ
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/bank HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}

###

GET {{HOST}}/bank? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bank?bank_id=1&bank_name=occaecat&bank_logo_url=https://uc HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}
###
PATCH {{HOST}}/bank/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"bank_id":"1",
"bank_name":"occaecat",
"bank_logo_url":"https://ucode.ai"
}
###
DELETE {{HOST}}/bank/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
