@HOST = https://alifpaywalletapi.azurewebsites.net

@HOSTL=http://localhost:8080
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhODdlNDk4MS0xOWZiLTQ3MDYtOTgwZS04ZWQwMGIxYTIwOGQiLCJlbWFpbCI6ImV4Y29kZS5uZXRAZ21haWwuY29tIiwibmFtZSI6IkFmbmFuIEFobWVkIiwidXNlcm5hbWUiOiJhZm5hbiIsImNvdW50cnkiOiIxMzAiLCJtb2JpbGVubyI6IjYwMTc2NzAxOTQ1IiwidWlkIjoiMTE3MjcwIiwiaWF0IjoxNzIyMzg5MDcxLCJleHAiOjE3MjQ5ODEwNzF9.MKR9AqN8t4jv08UAMBJPQQLVlcUvHXJOTF4JqMkMKqs
@API =https://mobile.alifpay.com.my/api/register
@N= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTFlYjRmMC1kYzdlLTQzNTUtODQxMS0wNDZhNGEzNWI0YjAiLCJlbWFpbCI6ImthemFkNzlAZ21haWwuY29tIiwibmFtZSI6Ik1EIEFidWwgS2FsYW0gQXphZCIsInVzZXJuYW1lIjoia2FsYW0iLCJjb3VudHJ5IjoiMTgiLCJtb2JpbGVubyI6IjYwMTc2NzAxOTQ2IiwidWlkIjoiMTE3MjAxIiwiaWF0IjoxNzE5MTk0NTI1LCJleHAiOjE3MTkxOTYzMjV9.NeSAV0F9Ft9VRfVmQe_7soCRHzA0X1S9isyz2YrLpl8
@AUTH_MYPAAA = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZTVkNjEwYy02NThhLTQ3MDItODk4OS1iOWI4NTBjZjdkOTYiLCJlbWFpbCI6ImthbGFtQG15cGFhYS5jb20iLCJuYW1lIjoiTXlQYWFhIFNkYiBCaGQiLCJjb3VudHJ5IjpudWxsLCJ1c2VybmFtZSI6Im15cGFhYSIsImJhbGFuY2UiOiI0NDQuNTUiLCJyZWZyZXNoS2V5IjoiVTBnY0RlSkZOdHl5eEpab281eHE1UT09IiwiaWF0IjoxNzE1OTE4MTA3fQ.VTPm9lMp3s7J9DyV3Z1MaOpe3SLCcIv49rv5sYHpxx0

@AUTH_Y =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNjNjMzM1Ny02YzVkLTQ2M2UtYjFkNi0yNTgxOWY2ZDlmZjEiLCJlbWFpbCI6ImthemFkNzlAeWFob28uY29tIiwibmFtZSI6IkthbGFtIEF6YWQiLCJjb3VudHJ5IjpudWxsLCJ1c2VybmFtZSI6ImthbGFtMiIsImJhbGFuY2UiOiIwLjAwIiwicmVmcmVzaEtleSI6Imx4c2ZtK2N4M2J0bHdEbTAwYWxTZWc9PSIsImlhdCI6MTcxNTk5OTc5MH0.7HrBWQ7WnbvH_kQ2rSjWTm9DwP1cA9xNRT2QYFV_nsU

@AUTH_EX =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0OTNmZDQ5Yy1hOWQwLTRhNzEtYmVhYS01MDA0OWE0OTVlODkiLCJlbWFpbCI6ImV4Y29kZS5uZXRAZ21haWwuY29tIiwidWlkIjowLCJuYW1lIjoiRXhDb2RlIERpZ2l0YWwiLCJ1c2VybmFtZSI6ImV4Y29kZTIiLCJjb3VudHJ5IjpudWxsLCJtb2JpbGVubyI6bnVsbCwicmVmcmVzaEtleSI6IlJZdm1XRnc3ZlZEbStZVVF1czZsYVE9PSIsImlhdCI6MTcxNjA4NjQwOX0.f4G6G8DMVVtdnqC289L4-usRZg8HHey5uMnUni5LvHM

@AUTH_A = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTFlYjRmMC1kYzdlLTQzNTUtODQxMS0wNDZhNGEzNWI0YjAiLCJlbWFpbCI6ImthemFkNzlAZ21haWwuY29tIiwibmFtZSI6IkthbGFtIEF6YWQiLCJ1c2VybmFtZSI6ImthbGFtIiwiY291bnRyeSI6IjE4IiwibW9iaWxlbm8iOiI2MDE3NjcwMTk0NiIsInVpZCI6IjAiLCJpYXQiOjE3MTk4MjgwODUsImV4cCI6MTcxOTgyOTg4NX0.uHyzJMD6LUv4fePgyps1DBryWPZIJVn03pThLn5P45I
@AUTH_AF =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTI1MmRlYy00NzIyLTQxNDAtYjAyYy1mNGFiMTEyMDZkMTYiLCJlbWFpbCI6ImZvdW5kZXJAd2luYW5kd2luZ3MuY29tIiwidWlkIjowLCJuYW1lIjoiQWZpYSBNdWJhc3NoaXJhIiwidXNlcm5hbWUiOiJhZmlhIiwiY291bnRyeSI6IiIsIm1vYmlsZW5vIjoiMDE3NjcwMTk4MCIsInJlZnJlc2hLZXkiOiJQOTh4T3NGUnIraHVIZlQ0bHJhaXVRPT0iLCJpYXQiOjE3MTYzNDIwMDZ9.utvebdXwK8R_RNWPQdyioGGIrhCF2IuSCqoz6Cs4p3c

@AU = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTFlYjRmMC1kYzdlLTQzNTUtODQxMS0wNDZhNGEzNWI0YjAiLCJlbWFpbCI6ImthemFkNzlAZ21haWwuY29tIiwidWlkIjoiMTE3MjAxIiwibmFtZSI6Ik1EIEFidWwgS2FsYW0gQXphZCIsInVzZXJuYW1lIjoia2FsYW0iLCJjb3VudHJ5IjoiMTgiLCJtb2JpbGVubyI6IjYwMTc2NzAxOTQ2IiwicmVmcmVzaEtleSI6IkNUQ2JRaWE4TDVNeEtBOHVxM0dHQUE9PSIsImlhdCI6MTcxOTE4NzU0MCwiZXhwIjoxNzE5MTg5MzQwfQ.DpBrWWuXj2yEeF7ySIuG3m0bKtTekWAGoNGm4vxPe-I
@ST =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZGVjNjE1Ny1jZDY3LTQwZDYtODQxNi01MmVhMzQwMjliOTgiLCJlbWFpbCI6ImVuLjI1NTIwMDBAZ21haWwuY29tIiwidWlkIjoiMTQzNTUxIiwibmFtZSI6IkxFRSBTRUUgRU4iLCJ1c2VybmFtZSI6InN0ZXZlIiwiY291bnRyeSI6IjEzMCIsIm1vYmlsZW5vIjoiNjAxMTEwODIxODIzIiwicmVmcmVzaEtleSI6InF0K1l5V3JQWEkzNFZYamczTlljWWc9PSIsImlhdCI6MTcyMDc0ODA2MSwiZXhwIjoxNzIwNzQ5ODYxfQ.-Azpnq1KUsVYgGpxI0yp0IiRnU25fwaykojwK6WEcYo
@AUTH_S=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZTQyOWQ4Mi05YWU3LTQ1YzAtODk2Ni04ZmIwMDNhM2VhNzAiLCJlbWFpbCI6InNoYXJtaW4xMTI3QGdtYWlsLmNvbSIsInVpZCI6MCwibmFtZSI6InNoYXJtaW4iLCJ1c2VybmFtZSI6InNoYXJtaW4iLCJjb3VudHJ5IjpudWxsLCJtb2JpbGVubyI6bnVsbCwicmVmcmVzaEtleSI6ImVlVjNQWmdkNVBwOWw0QkEyTjR4Y2c9PSIsImlhdCI6MTcxNjQ0NzM4Mn0.istVUMbqfoqEhhvu8WCCjloTbr4HfLki3eJ7RjJ0ZhE
GET {{HOSTL}}/mpay/casa/banklist HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json


###
GET {{HOSTL}}/mpay/casa/bankAccList HTTP/1.1
Authorization: Bearer {{AUTH}} 
content-type: application/json


###
POST {{HOSTL}}/mpay/casa/bankEnroll HTTP/1.1
Authorization: Bearer {{AUTH}} 
content-type: application/json

{
   "acc_no":"38704598610",
   "acc_desc":"459-045986-108 ",
   "acctype_id":"1",
   "bank_id":"3"
}

###
POST {{HOSTL}}/mpay/casa/uploadbankdoc HTTP/1.1
Authorization: Bearer {{AUTH}} 
content-type: application/json

{
   "accNo":"128704598610"

}

###
POST {{HOSTL}}/mpay/casa/removebankacc HTTP/1.1
Authorization: Bearer {{AUTH}} 
content-type: application/json

{
   "accNo":"129045986102",
   "bankId":"109"

}



###
POST {{HOSTL}}/mpay/casa/casafundtransfer HTTP/1.1
Authorization: Bearer {{AUTH}} 
content-type: application/json

{
   "bankId":"108",
   "cardpin":"",
   "amount":"100.00",
   "reference":"WITHDRAW"

}
